### ISSUE TITLE
Android Language settings doesn't list any languages

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-xulrunner#257]

**Comment by mhutti1** [comment]
This occurs when locales.txt is not generated by the build script. We should probably implement a warning if it doesn't exist.

**Comment by kelson42** [comment]
The explanation is: This list is populated by android/assets/locales.txt. This is generated by ./build-android-with-native.py --locales. As a consequence this file is not in the git (or at least I have removed it for that reason). The problem is for users using only the Android Studio... I have reintroduced it. Problem solved.
