### ISSUE TITLE
Wikimed ES not able to start at all with Android 6.0.1

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#316]
I just have upgraded to android 6.0.1 my samsung tablet. I have newly installed Wikimed ES and the app does not start and complains about an overlay problem, I should configure something in the settings of the app. Then I get this screenshot, but impossible to switch the parameter ON, it stay greys. The Twitter app for example is ON (green) without I had to do anything. I think here we have forgotten about a permission.
![screenshot](https://cloud.githubusercontent.com/assets/1029718/18623873/68a7ec50-7e42-11e6-8bc0-b857bfefc9b1.png)

Info: My android does not have dimly or twillight installed

**Comment by kelson42** [comment]
Now it works... no clue why.

**Comment by kelson42** [comment]
I have the problem with all newly installed custom apps.. here is seriously something wrong.

**Comment by mhutti1** [comment]
@kelson42 You have got the wrong end of the stick here. When you are redirected to that page it shows all apps that have permission to draw over our app. There is nothing that we as an app can do to stop this. Android will not grant us the permission that we need until  there are no apps drawing over us. In order to allow android to grant us this permission you must disable all apps that are currently drawing over our screen. I don't know how I can explain it better but there is nothing that we can do at this time.

**Comment by kelson42** [comment]
OK, I have deactivated all the apps with that overlay permission and it was OK, no clue which one was the root of the problem
