### ISSUE TITLE
can't go back from search activity triggered from widget

### ISSUE THREAD

**Issue by EladKeyshawn** [kiwix/kiwix-xulrunner#428]
I do not know if this happens only to me, but when search activity is triggered from the search widget the back arrow or button won't work.

**Comment by EladKeyshawn** [comment]
@mhutti1  any ideas?

**Comment by mhutti1** [comment]
@EladKeyshawn Yeah I commented on your code. Its to do with intents. Basically when you click the widget we launch the main activity to initialise our app if its not open. Then this activity starts the Search activity with an intent. The intent that it stats it with is kind of the same. I think it might even be the same in order to conserve resources. So what happens is we call the search activity and it still has the action from the widget. Well this is no problem when searching but when you then try to exit the same intent is passed back to the main activity. This causes the main activity to assume that it was launched from the search widget and so it launches the search activity,

**Comment by EladKeyshawn** [comment]
@mhutti1 Now I've changed the code to use the actions sent from the widget instead of intents. but still same result.

**Comment by mhutti1** [comment]
@EladKeyshawn I don't quite understand. The way I worked out to fix it was to simply reset the action before then stating another activity. What have you done?

**Comment by EladKeyshawn** [comment]
@mhutti1 Oh ok now I get what you saying...

**Comment by EladKeyshawn** [comment]
@mhutti1 I've just changes the behaviour to use the actions instead of mere intents. I forgot to reset back the action ;)

**Comment by mhutti1** [comment]
@EladKeyshawn Yeah it took me a lot of debugging when I first encountered this issue to work out intents are reused along with their Extras and Actions.

**Comment by mhutti1** [comment]
@EladKeyshawn Any chance you could push your fix for this?

**Comment by EladKeyshawn** [comment]
@mhutti1 I did push it 😕

**Comment by mhutti1** [comment]
@EladKeyshawn I can't see it in the history and its still broken for me.

**Comment by EladKeyshawn** [comment]
@mhutti1  Your're right I thought i did... now done
