### ISSUE TITLE
Custom widget for custom apps

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#45]
- Logo should be replace by custom app logo
- "Search Kiwix" shoudl be replaced by "Search app_name"

**Comment by kelson42** [comment]
@EladKeyshawn Any news on this?

**Comment by mhutti1** [comment]
Steps to reproduce:
1. Setup our virtual machine (or configure your own environment)
2. Cd to the main android directory.
3. Make a placeholder content file called custom/wikimed/content.zim that is empty.
4. Run ./gen-custom-android-build.py custom/wikimed/info.json
5. Install the generated apk in build/outputs/apk/ on your device.
6. Create a widget and you will see the main Kiwix logo instead of the custom app log.

What you get:
- The Kiwix logo instead of the custom app logo.

What we want:
- Custom app logo replaces the Kiwix logo in the widget. (This might require reading the python script that you ran to generate the custom app)

**Comment by mhutti1** [comment]
This now works correctly although the preview is not correct. Short of creating a complicated script to edit a stock image for each app or defaulting to the app icon having one app unspecific preview image seems like the only way to go so I have updated our current one to reflect this.

be522788ee0e5083642b540b1db8e42ca850ce57

Great work @borisfba 👍
